	#base	"../../custom/resource/ui/huditemeffectmeter_engineer.res"
	#base	"../../#users/dane/resource/ui/huditemeffectmeter_engineer.res"
	#base	"../../_csgo/resource/ui/huditemeffectmeter_engineer.res"
	#base	"../../_opd/resource/ui/huditemeffectmeter_engineer.res"
	#base	"../../_def/resource/ui/huditemeffectmeter_engineer.res"